version: '3'
services:
  rumba-teste:
    image: image-debian1:latest
    ports:
      - "1180:80"
      - "11443:443"
      - "1122:22"
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/logs/apache2
